import fs from 'node:fs';
import http from 'node:http';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const scriptDir = path.dirname(fileURLToPath(import.meta.url));
const projectRoot = path.resolve(scriptDir, '..');
const evidenceDir = path.join(projectRoot, 'scratch', 'run-evidence');
const cleanTargetDir = path.join(projectRoot, 'scratch', 'clean-safe');
const manualCacheDir = path.join(projectRoot, 'scratch', 'manual-cache');

if (process.argv.includes('--write-clean-targets')) {
  writeCleanTargets();
  console.log(`[launchdeck-demo-api] clean targets ready under ${path.relative(projectRoot, cleanTargetDir)}`);
  process.exit(0);
}

const port = resolvePort();
writeStartupEvidence(port);

const startedAt = new Date().toISOString();
let requestCount = 0;

const server = http.createServer((request, response) => {
  requestCount += 1;
  const requestStartedAt = new Date().toISOString();
  console.log(`[launchdeck-demo-api] request method=${request.method} url=${request.url} count=${requestCount}`);

  if (request.url === '/health') {
    sendJson(response, 200, {
      ok: true,
      service: 'launchdeck-demo-api',
      pid: process.pid,
      port,
      startedAt,
      requestCount
    });
    return;
  }

  if (request.url === '/events') {
    sendJson(response, 200, {
      events: [
        {
          type: 'request',
          at: requestStartedAt,
          count: requestCount
        }
      ]
    });
    return;
  }

  if (request.url === '/_demo/exit') {
    sendJson(response, 200, {
      ok: true,
      message: 'Demo server exiting so Launchdeck can reconcile stale state.'
    });
    setImmediate(() => shutdown('demo-exit'));
    return;
  }

  sendJson(response, 200, {
    message: 'Launchdeck demo API is running.',
    health: '/health',
    events: '/events',
    demoExit: '/_demo/exit'
  });
});

server.listen(port, '127.0.0.1', () => {
  const address = server.address();
  console.log(`[launchdeck-demo-api] ready url=http://127.0.0.1:${address.port} pid=${process.pid}`);
  console.log(`[launchdeck-demo-api] launchdeck task=${process.env.LAUNCHDECK_TASK ?? 'manual'} run=${process.env.LAUNCHDECK_RUN_ID ?? 'manual'}`);
  console.log(`[launchdeck-demo-api] clean preview target=${path.relative(projectRoot, cleanTargetDir)}`);
});

const heartbeat = setInterval(() => {
  console.log(`[launchdeck-demo-api] heartbeat pid=${process.pid} requests=${requestCount}`);
}, 15_000);
heartbeat.unref();

process.on('SIGINT', () => shutdown('SIGINT'));
process.on('SIGTERM', () => shutdown('SIGTERM'));

function resolvePort() {
  const argvPort = readArgValue('--port') ?? firstNumericArg();
  const rawPort = argvPort ?? process.env.PORT ?? '8888';
  const parsedPort = Number(rawPort);
  if (!Number.isInteger(parsedPort) || parsedPort < 1 || parsedPort > 65535) {
    console.error(`[launchdeck-demo-api] invalid port: ${rawPort}`);
    process.exit(2);
  }
  return parsedPort;
}

function readArgValue(name) {
  const index = process.argv.indexOf(name);
  if (index === -1) {
    return undefined;
  }
  return process.argv[index + 1];
}

function firstNumericArg() {
  return process.argv.slice(2).find((arg) => /^\d+$/.test(arg));
}

function sendJson(response, statusCode, body) {
  response.writeHead(statusCode, {
    'content-type': 'application/json',
    'cache-control': 'no-store'
  });
  response.end(JSON.stringify(body));
}

function writeStartupEvidence(listenPort) {
  fs.mkdirSync(evidenceDir, { recursive: true });
  fs.writeFileSync(
    path.join(evidenceDir, 'last-start.json'),
    `${JSON.stringify({
      pid: process.pid,
      port: listenPort,
      startedAt: new Date().toISOString(),
      launchdeckHome: process.env.LAUNCHDECK_HOME,
      launchdeckProjectId: process.env.LAUNCHDECK_PROJECT_ID,
      launchdeckRunId: process.env.LAUNCHDECK_RUN_ID,
      launchdeckTask: process.env.LAUNCHDECK_TASK
    }, null, 2)}\n`
  );
  writeCleanTargets();
}

function writeCleanTargets() {
  fs.mkdirSync(cleanTargetDir, { recursive: true });
  fs.mkdirSync(manualCacheDir, { recursive: true });
  fs.writeFileSync(
    path.join(cleanTargetDir, 'delete-me.txt'),
    [
      'This file is generated by the demo server.',
      'It exists so `launchdeck clean --safe` can remove a target without deleting logs or run evidence.'
    ].join('\n') + '\n'
  );
  fs.writeFileSync(
    path.join(manualCacheDir, 'keep-until-clean-all.txt'),
    'This risky target is present for cleanup preview demonstrations.\n'
  );
}

function shutdown(signal) {
  console.log(`[launchdeck-demo-api] shutting down signal=${signal}`);
  clearInterval(heartbeat);
  server.close(() => {
    console.log('[launchdeck-demo-api] stopped');
    process.exit(0);
  });
  setTimeout(() => {
    console.log('[launchdeck-demo-api] forced shutdown timeout elapsed');
    process.exit(0);
  }, 2_000).unref();
}
