# Generated by Django 5.2.0 on 2026-08-04 00:00

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(max_length=80, unique=True)),
                ("title", models.CharField(max_length=160)),
                ("description", models.TextField()),
                ("venue", models.CharField(max_length=120)),
                ("starts_at", models.DateTimeField()),
                ("capacity", models.PositiveIntegerField()),
                ("is_free", models.BooleanField(default=True)),
            ],
            options={"ordering": ["starts_at", "slug"]},
        ),
    ]
